edition = "2023";

import "scenario.proto";
import "playlist.proto";
import "guide.proto";

package aim;

message BundleScenario {
  string name = 1;
  ScenarioDef def = 2;
}

message BundlePlaylist {
  string name = 1;
  PlaylistDef def = 2;
}

message BundleGuide {
  string name = 1;
  GuideDef def = 2;
}

message BundleFile {
  repeated BundleScenario scenarios = 1;
  repeated BundlePlaylist playlists = 2;
  repeated BundleGuide guides = 3;
}

message BundleInfo {
  string bundle_name = 1;
  bool readonly = 2;
  bool archived = 3;
}

// Structure for bundles.json file.
message BundleInfoFile {
  repeated BundleInfo bundles = 1;
}
