edition = "2023";

import "common.proto";

package aim;

// Room defined by dimensions of the back wall the user is facing.
message SimpleRoom {
  float height = 1;
  float width = 2;
  float depth = 3;
}

message CylinderRoom {
  float height = 1;
  float radius = 2;
  // The width of the wall to use for target placement and to draw sides.
  float width = 3;
  // Instead of an absolute width, define as percent of perimeter. 0.5 is 180 degree view.
  float width_perimeter_percent = 4;
  // Instead of an absolute width, define as degrees. i.e. 180 degree view.
  float width_degrees = 7;

  // Draw sides to the room at the specified angle. These walls are drawn based on the width of the
  // wall.
  float side_angle_degrees = 6;
}

// Similar to a cylinder room but turned on its side. The target wall is a circle.
message BarrelRoom {
  float radius = 1;
}

message Room {
  StoredVec3 camera_position = 1;
  // Default to (0,0,1)
  StoredVec3 camera_up = 2;
  // Default to (0,1,0)
  StoredVec3 camera_front = 3;

  float start_pitch = 4;
  float start_yaw = 5;

  // Initialize the camera to look at this point on the wall.
  RegionVec2 look_at_point = 7;

  // Defaults to 103
  float horizontal_fov = 6;

  oneof type {
    SimpleRoom simple_room = 21;
    CylinderRoom cylinder_room = 22;
    BarrelRoom barrel_room = 23;
  }
}

message RegionLength {
  oneof type {
    // Length is a percent of relevant dimension (x,y) on the wall.
    float x_percent_value = 1;
    float y_percent_value = 2;
    float depth_percent_value = 3;
    float value = 4;
  }
}

message RegionVec2 {
  RegionLength x = 1;
  RegionLength y = 2;
}

message TargetRegion {
  ProfileInfo info = 1;

  // (0, 0) is the center of the wall.
  RegionLength x_offset = 2;
  RegionLength y_offset = 3;

  // The distance in from the wall to place the target. The larget the depth, the closer to the
  // camera. 0 depth is on the wall.
  RegionLength depth = 4;
  RegionLength depth_jitter = 5;

  // The next target will be placed at the specified distance from the last target. The target is
  // placed within the region and then the target is moved straight towards the last target until at
  // the correct distance.
  RegionLength fixed_distance_from_last_target = 6;
  // If using fixed distance allow the distance to vary by this amount. i.e. +/- jitter.
  RegionLength fixed_distance_from_last_target_jitter = 7;

  oneof type {
    RectangleTargetRegion rectangle = 10;
    EllipseTargetRegion ellipse = 11;
    CircleTargetRegion circle = 12;
    RegionVec2 point = 13;
  }
}

// [json_name = "modernName"]
message RectangleTargetRegion {
  RegionLength x_length = 1;
  RegionLength y_length = 2;

  // If specified the inner rectangle will be cut out. If only 1 of x or y is specified then the
  // other dimension will be assumed the full length resulting in two rectangular regions.
  RegionLength inner_x_length = 3;
  RegionLength inner_y_length = 4;
}

message EllipseTargetRegion {
  RegionLength x_diameter = 1;
  RegionLength y_diameter = 2;
}

message CircleTargetRegion {
  RegionLength diameter = 1;
  // Optional. If specified the region will be a donut.
  RegionLength inner_diameter = 2;
}

message TargetPlacementStrategy {
  repeated TargetRegion regions = 1;
  ProfileListInfo regions_info = 2;

  RegionLength min_distance = 3;

  RegionLength min_x_distance = 6;
  RegionLength min_y_distance = 7;
}

message ScenarioOverrides {
  float target_radius_multiplier = 3;
  float speed_multiplier = 4;
  float acceleration_multiplier = 5;
  float time_scale_multiplier = 6;
  float distance_multiplier = 7;
  float growth_time_multiplier = 8;
  float remove_target_after_seconds_multiplier = 9;
  float fixed_distance_from_last_target_multiplier = 10;
  float min_distance_multiplier = 11;
  float wall_width_multiplier = 12;
  float wall_height_multiplier = 13;
  float level_offset = 14;
}

message ReloadInfo {
  int32 max_shots = 1;
  int32 num_to_reload_on_hit = 2;
  float reload_time = 3;
}

enum AccuracyPenalty {
  // will default to sqrt
  ACCURACY_PENALTY_UNKNOWN = 0;
  // hits * sqrt(hit_percent)
  ACCURACY_PENALTY_SQRT = 1;
  ACCURACY_PENALTY_NONE = 2;
}

message ShotType {
  oneof type {
    // Targets are killed after being "tracked"" consistently for a short duration. Typical for
    // static scenarios. Mouse does not need to be held done or clicked.
    bool poke = 1;
    // Targets have health and must be traced for a certain amount of time.
    bool tracking_kill = 2;
    // A single target will be tracked and the total time on target will be the score.
    bool tracking_invincible = 3;
    // Target takes a single click to kill.
    bool click_single = 4;
    // Targets take multiple clicks to kill where the number of clicks is specified on the target.
    bool click_multi = 5;
    // A single invincible target is tracked. The score is based on how close to the center you are
    // and not the size of the target which is just visual.
    bool tracking_proximity = 6;
    // Poke with an instant kill time.
    bool poke_instant = 7;
  }
  // If unset defaults to 0.05 (50 millis)
  float poke_kill_time_seconds = 10;

  // Partial kills are not counted towards score.
  bool no_partial_kills = 11 [features.field_presence = IMPLICIT];

  // For tracking kill, the amount of time it takes to kill.
  float health_seconds = 12;

  // The rate for health to regen if a target with health is not killed. 1 means to regen at the
  // same rate as health is taken away. So 2 means regen twice as fast as it is killed.
  float health_regen_rate = 13;

  // Remove the target if it has less than the specified health time left and you are no longer on
  // target.
  float remove_if_below_health_seconds = 14;

  // For multi click, the number of clicks to kill the target.
  int32 health_clicks = 16;

  // If specified, you can only click at the given rate.
  float click_rate_seconds = 17;

  // Target will become a ghost on miss and be removed after the specified amount of time.
  float ghost_closest_on_miss = 18;
  // The target won't be removed after the time is up. It will just become clickable again.
  bool unghost_miss_on_expiration = 22 [features.field_presence = IMPLICIT];

  // For clicking scenarios, remove the target if you miss it.
  bool remove_closest_on_miss = 19 [features.field_presence = IMPLICIT];

  // Disables accuracy penalty but you will need to reload if you miss too many consecutive shots.
  ReloadInfo reload = 20;
  AccuracyPenalty accuracy_penalty = 21;
}

// Defines the target score and optional ranks associated with levels (TODO).
// You get a score of 5 if you hit the target score. 4 for 95% of target. 3=90%, 2=85%, 1=80%.
// 0-1 is proportionally scored from 0 up to 80%. So a 40% score would get 0.5.
message ScoreTargets {
  float target_score = 1;
}

message ScenarioDef {
  string description = 1 [features.field_presence = IMPLICIT];
  int32 duration_seconds = 2;
  ShotType shot_type = 3;
  TargetDef target_def = 4;
  Room room = 5;

  ScenarioOverrides overrides = 7;

  // Defines the automatically created variations L1,L2,... and L-1,L-2,...
  ScenarioOverrides level_overrides = 8;

  ScoreTargets score_targets = 9;

  oneof type {
    StaticScenarioDef static_def = 30;
    CenteringScenarioDef centering_def = 31;
    BarrelScenarioDef barrel_def = 32;
    LinearScenarioDef linear_def = 33;
    AngleStrafeScenarioDef angle_strafe_def = 34;
    WallArcScenarioDef wall_arc_def = 35;
    WallWanderScenarioDef wall_wander_def = 36;
    ReferenceScenarioDef reference_def = 37;
    CircleScenarioDef circle_def = 38;
    SineScenarioDef sine_def = 39;
    WaypointScenarioDef waypoint_def = 40;
    StrafeScenarioDef strafe_def = 41;
    BounceScenarioDef bounce_def = 42;
  }
}

// This scenario extends the specified scenario optionally specifying overrides to tweak settings.
message ReferenceScenarioDef {
  string scenario_name = 1;
  ShotType shot_type = 2;
  int32 duration_seconds = 3;
  int32 num_targets = 4;
  Room room = 5;
  string description = 6;

  // Overrides the target radius with an explicit value. Useful for defining a stable base level in
  // a ladder playlist. This will update the radius in the first profile and all other profiles will
  // keep their relative size based on the new radius.
  float explicit_target_radius = 7;

  float horizontal_fov = 8;
}

message StaticScenarioDef {
  TargetPlacementStrategy target_placement_strategy = 1;
}

message CircleScenarioDef {
  RegionLength radius = 1;
  // The starting point in degrees. 0 degrees is straight to the right and it rotates counter
  // clockwise.
  float start_degrees = 2;
  bool rotate_clockwise = 3 [features.field_presence = IMPLICIT];
  RegionLength depth = 4;
  float switch_after_seconds = 5;

  float stretch_y = 6;
  float stretch_x = 7;

  // If specified the target radius will change to this over time.
  RegionLength final_radius = 8;
}

message CenteringScenarioDef {
  // Target will move from point to point and then recycle through the list.
  repeated RegionVec2 wall_points = 1;

  // Goes between two points at the specifed number of degress for the given length.
  float angle = 4;
  float angle_jitter = 5;
  RegionLength angle_length = 6;
}

message WaypointScenarioDef {
  TargetPlacementStrategy target_placement_strategy = 1;
  bool start_in_center = 2 [features.field_presence = IMPLICIT];
}

message BarrelScenarioDef {
  // Typically a Cirle region with the middle missing.
  TargetPlacementStrategy target_placement_strategy = 1;
  // When targets spawn or hit a wall they will be directed towards a point in the center percent of
  // the barrel.
  float direction_radius_percent = 2;
}

enum Direction {
  DIRECTION_RANDOM = 0;
  DIRECTION_POSITIVE = 1;
  DIRECTION_NEGATIVE = 2;
  DIRECTION_IN = 3;
  DIRECTION_OUT = 4;
}

// Targets move linearly within the specified room. Uses 2d wall placement so it support simple room
// types.
message LinearScenarioDef {
  // O degrees would move horizontally. 90 degrees would move vetically. Values must be between
  // 0-90.
  float angle = 1;
  float angle_jitter = 2;

  TargetPlacementStrategy target_placement_strategy = 5;

  Direction left_right_initial_direction = 6;
  Direction up_down_initial_direction = 7;
}

message SineScenarioDef {
  // Amplitude.
  RegionLength height = 1;
  // Period.
  RegionLength width = 2;
  bool going_left = 3 [features.field_presence = IMPLICIT];
}

// General information for an individual profile in a list. Shared by all profile list types.
// This will be embedded in the specific profile type like StrafeProfile.
message ProfileInfo {
  string description = 1 [features.field_presence = IMPLICIT];
  // Proportional weight used to select this profile. If the weight of this profile is 2 and the
  // other is 1, then this profile will be used 2/3 of the time.
  float weight = 2;

  int32 next_profile = 3;
  // 1 means that 1 other profile must be selected before this one can be selected again.
  // 2 means that 2 other profiles (maybe the same profile both times) must be selected ...
  int32 min_selection_gap = 4;
}

message ProfileListInfo {
  // If non empty, profiles will be chosen in the specified pattern repeating. 0 indexed.
  repeated int32 explicit_order = 1;

  // If non empty, profiles will be chosen in the specified order at the start and then will proceed
  // to normal profile selection.
  repeated int32 start_order = 2;
}

message AngleStrafeProfile {
  ProfileInfo info = 1;

  RegionLength distance = 2;
  RegionLength distance_jitter = 3;

  // Angle to strafe at. In range 0-45. Will choose between strafing up or down at this angle
  // evenly.
  float angle = 7;
  float angle_jitter = 8;
  // The chance that the strafe will change direction vertically. i.e. Switch from strafing up to
  // down at the specified angle. Defaults to 0.5, 50/50 chance.
  float direction_change_percent = 9;

  // Allows increasing to very high value to create a teleport like effect.
  float speed_multiplier = 13;
  float speed_multiplier_jitter = 15;

  float acceleration_multiplier = 14;
  float acceleration_multiplier_jitter = 16;

  // Distance is updated by this value based on whether it is moving towards/away
  // from the center to encourage the target to stay closer to center.
  float center_bias = 17;
}

message Bounds {
  RegionLength width = 1;
  RegionLength height = 2;
  RegionLength depth = 3;
}

// Strafe sceanrio where it strafes back and forth at angles on the wall. When it changes left/right
// direction it can optionally also change up/down direction.
message AngleStrafeScenarioDef {
  Bounds bounds = 1;

  TargetPlacementStrategy target_placement_strategy = 2;

  repeated AngleStrafeProfile profiles = 4;
  ProfileListInfo profiles_info = 5;

  repeated StrafeProfile forward_back_profiles = 6;
  ProfileListInfo forward_back_profiles_info = 7;
  Direction forward_back_initial_direction = 8;
}

message StrafeProfile {
  ProfileInfo info = 1;

  float time = 2;
  float time_jitter = 3;

  // Time/distance is updated by this value based on whether it is moving towards/away
  // from the center to encourage the target to stay closer to center.
  float center_bias = 4;

  RegionLength distance = 5;
  RegionLength distance_jitter = 6;

  float speed_multiplier = 7;
  float speed_multiplier_jitter = 8;

  float acceleration_multiplier = 9;
  float acceleration_multiplier_jitter = 10;

  // Will pause for the specified time at the end of the strafe.
  float pause_time = 11;
  float pause_time_jitter = 12;

  // If specified, percent chance pause will happen. 0.5 = 50% chance.
  float pause_chance_percent = 13;

  float target_radius_multiplier = 14;
  float target_radius_multiplier_jitter = 15;

  // For a new target starting with this profile. Start with an initial velocity x% of the max
  // velocity. This is only relevant for targets with acceleration. 1 will start at full speed.
  // 0.5 at half speed.
  float start_speed_percent = 16;
}

message StrafeScenarioDef {
  Bounds bounds = 1;
  Bounds relative_bounds = 2;

  TargetPlacementStrategy target_placement_strategy = 4;

  repeated StrafeProfile left_right_profiles = 5;
  ProfileListInfo left_right_profiles_info = 6;

  repeated StrafeProfile forward_back_profiles = 7;
  ProfileListInfo forward_back_profiles_info = 8;

  repeated StrafeProfile up_down_profiles = 9;
  ProfileListInfo up_down_profiles_info = 10;

  Direction left_right_initial_direction = 13;
  Direction up_down_initial_direction = 14;
  Direction forward_back_initial_direction = 15;
}

message BounceProfile {
  ProfileInfo info = 1;

  RegionLength height = 2;
  RegionLength height_jitter = 3;

  float delay_seconds = 4;
  float delay_seconds_jitter = 5;
  bool only_delay_on_floor = 6 [features.field_presence = IMPLICIT];

  float speed_multiplier = 7;
  float speed_multiplier_jitter = 8;

  float acceleration_multiplier = 9;
  float acceleration_multiplier_jitter = 10;

  // Time to pause vertically at the top of the bounce.
  float float_time = 11;
  float float_time_jitter = 12;

  // Speed and acceleration overrides for the downward portion of the bounce. Applied in addition to
  // any other profile specific multipliers.
  float down_speed_multiplier = 13;
  float down_speed_multiplier_jitter = 14;

  float down_acceleration_multiplier = 15;
  float down_acceleration_multiplier_jitter = 16;
}

message BounceScenarioDef {
  Bounds bounds = 1;
  Bounds relative_bounds = 2;

  repeated BounceProfile bounce_profiles = 3;
  ProfileListInfo bounce_profiles_info = 4;

  repeated StrafeProfile left_right_profiles = 5;
  ProfileListInfo left_right_profiles_info = 6;

  repeated StrafeProfile forward_back_profiles = 7;
  ProfileListInfo forward_back_profiles_info = 8;

  TargetPlacementStrategy target_placement_strategy = 9;

  Direction left_right_initial_direction = 11;
  Direction forward_back_initial_direction = 12;

  RegionLength floor_height = 13;
  bool start_on_floor = 14 [features.field_presence = IMPLICIT];
}

message WallArcScenarioDef {
  // The spline will be stretched to fit in a box with specified height/width centered around 0,0 on
  // the wall.
  RegionLength width = 1;
  RegionLength height = 2;
  RegionLength height_jitter = 3;

  bool start_on_ground = 6 [features.field_presence = IMPLICIT];

  // Make the arc upside down.
  bool reflect = 7 [features.field_presence = IMPLICIT];
}

message WallWanderProfile {
  ProfileInfo info = 1;

  float turn_time = 2;
  float turn_time_jitter = 3;

  float turn_rate = 4;
  float turn_rate_jitter = 5;
}

message WallWanderScenarioDef {
  TargetPlacementStrategy target_placement_strategy = 1;

  repeated WallWanderProfile profiles = 2;
  ProfileListInfo profiles_info = 3;
}

message TargetDef {
  int32 num_targets = 1;
  repeated TargetProfile profiles = 2;
  ProfileListInfo profiles_info = 3;

  // The most recently placed target will not be clickable and will be
  // displayed with a separate color as determined by theme. This is
  // useful for forced pathing so you know where the target will be
  // but have to click in the correct order.
  bool newest_target_is_ghost = 5 [features.field_presence = IMPLICIT];

  // New targets will be added after the specified amount of seconds.
  float new_target_delay_seconds = 6;

  // A target will automatically be removed after the specified amount of seconds.
  float remove_target_after_seconds = 7;

  // The initial target will be added with the specified delay between each target.
  float stagger_initial_targets_seconds = 8;

  // A list of delays in seconds for targets to be initially added.
  repeated float delayed_target_times = 9;

  // If targets get within x% distance from the edge of the wall, they will become a ghost until
  // they return towards the center. This allows producing a smooth your wrist like no hit portion
  // at the end of the strafes.
  float ghost_border_percent = 10;
}

message PillTargetDef {
  float height = 1;
}

message TargetProfile {
  ProfileInfo info = 1;

  float target_radius = 2;
  float target_radius_jitter = 3;

  float speed = 4;
  float speed_jitter = 5;

  float acceleration = 6;
  float acceleration_jitter = 7;

  // Target will shrink from target_radius to this value based on health amount.
  float target_radius_at_kill = 8;

  // The target will grow to the specified size after n seconds.
  float target_radius_growth_time_seconds = 12;
  float target_radius_growth_size = 13;
  // The amount of time it will stay at final size before being removed. This time is in addition to
  // the growth size.
  float target_radius_growth_final_size_time_seconds = 14;

  // Defaults to spehere if no more specific type is specified.
  oneof type {
    PillTargetDef pill = 10;
  }
}
