edition = "2023";

import "common.proto";

package aim;

message HealthBarSettings {
  reserved 3, 4, 5;
  bool show = 1 [features.field_presence = IMPLICIT];
  bool only_damaged = 2 [features.field_presence = IMPLICIT];
  // 1.0 is a little larger than the target radius. Max value of 3.
  float size = 6;
}

enum MsaaLevel {
  MSAA_LEVEL_UNKNOWN = 0;
  MSAA_LEVEL_OFF = 1;
  MSAA_LEVEL_2X = 2;
  MSAA_LEVEL_4X = 4;
  MSAA_LEVEL_8X = 8;
}

message BackupSettings {
  bool disable_backups = 1 [features.field_presence = IMPLICIT];

  // Defaults to backing up every day.
  int32 backup_every_n_days = 2;

  int32 max_backups_to_keep = 3;
}

message Settings {
  float dpi = 1;
  float cm_per_360 = 2;
  string theme_name = 4;

  bool enable_metronome = 3 [features.field_presence = IMPLICIT];
  float metronome_bpm = 5;

  float crosshair_size = 6;
  string current_crosshair_name = 7;

  bool disable_click_to_start = 8 [features.field_presence = IMPLICIT];

  Keybinds keybinds = 9;

  // Left click is automatically held down in tracking scenarios.
  bool auto_hold_tracking = 10 [features.field_presence = IMPLICIT];

  HealthBarSettings health_bar = 12;

  bool disable_per_scenario_settings = 13 [features.field_presence = IMPLICIT];

  float max_render_fps = 14;

  // Vsync, immediate, mailbox
  PresentMode present_mode = 15;

  SoundSettings sounds = 16;

  // Time in seconds for a start countdown at the beginning of scenarios.
  float start_countdown_time = 17;

  ScenarioSettingsConfig scenario_settings_config = 18;

  // This is purely for audio and not actual scoring.
  float tracking_shots_per_second = 19;

  // Shot rate when furthest from center.
  float proximity_min_shots_per_second = 20;

  // Shot rate when at center.
  float proximity_max_shots_per_second = 21;

  bool disable_replays = 22;

  MsaaLevel msaa_level = 23;

  // By default the display with the highest refresh rate will be chosen.
  // Specify the name of a different display to use here if that is not correct.
  string explicit_display_name = 24;

  BackupSettings db_backups = 25;
}

message SoundItem {
  string name = 1;
  // Optional. Specific volume level for the sound.
  float volume_level = 2;
  // Optional. Modify the pitch of the sound.
  float pitch_modifier = 3;
}

message SoundSettings {
  // Percent value from 0 to 1.
  float master_volume_level = 1;

  SoundItem click_miss = 2;
  SoundItem click_hit = 3;
  SoundItem click_kill = 4;
  SoundItem reload = 5;

  SoundItem tracking_miss = 6;
  SoundItem tracking_hit = 7;
  SoundItem tracking_kill = 8;

  SoundItem metronome = 12;
}

message ScenarioSettings {
  reserved 6;
  float cm_per_360 = 1;
  string theme_name = 2;
  float metronome_bpm = 3;
  float crosshair_size = 4;
  string crosshair_name = 5;
  bool auto_hold_tracking = 7 [features.field_presence = IMPLICIT];
  HealthBarSettings health_bar = 8;
  bool enable_metronome = 9 [features.field_presence = IMPLICIT];
  float tracking_shots_per_second = 10;
}

enum ScenarioSettingsStoreType {
  SCENARIO_SETTINGS_STORE_TYPE_UNKNOWN = 0;
  // The setting is saved per scenario.
  STORE_PER_SCENARIO = 1;
  // The setting is used for all scenarios and comes from settings.json directly.
  STORE_GLOBALLY = 2;
}

// Configures which settings fields get saved per scenario and at what level.
message ScenarioSettingsConfig {
  ScenarioSettingsStoreType cm_per_360 = 1;
  ScenarioSettingsStoreType theme_name = 2;
  ScenarioSettingsStoreType metronome_bpm = 3;
  ScenarioSettingsStoreType crosshair_size = 4;
  ScenarioSettingsStoreType crosshair_name = 5;
  ScenarioSettingsStoreType auto_hold_tracking = 6;
  ScenarioSettingsStoreType health_bar = 7;
  ScenarioSettingsStoreType enable_metronome = 8;
  ScenarioSettingsStoreType tracking_shots_per_second = 9;
}

message KeyMapping {
  string mapping1 = 1;
  string mapping2 = 2;
  string mapping3 = 3;
  string mapping4 = 4;
}

message Keybinds {
  KeyMapping fire = 1;
  KeyMapping restart_scenario = 2;
  KeyMapping next_scenario = 3;
  KeyMapping quick_settings = 4;
  KeyMapping adjust_crosshair_size = 5;
  KeyMapping quick_metronome = 6;
  KeyMapping edit_scenario = 7;
}
