// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bundle.proto
// Protobuf C++ Version: 6.33.5

#include "bundle.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace aim {

inline constexpr BundleInfo::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        bundle_name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        readonly_{false},
        archived_{false} {}

template <typename>
PROTOBUF_CONSTEXPR BundleInfo::BundleInfo(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(BundleInfo_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct BundleInfoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BundleInfoDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~BundleInfoDefaultTypeInternal() {}
  union {
    BundleInfo _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BundleInfoDefaultTypeInternal _BundleInfo_default_instance_;

inline constexpr BundleInfoFile::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        bundles_{} {}

template <typename>
PROTOBUF_CONSTEXPR BundleInfoFile::BundleInfoFile(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(BundleInfoFile_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct BundleInfoFileDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BundleInfoFileDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~BundleInfoFileDefaultTypeInternal() {}
  union {
    BundleInfoFile _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BundleInfoFileDefaultTypeInternal _BundleInfoFile_default_instance_;

inline constexpr BundlePlaylist::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        def_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR BundlePlaylist::BundlePlaylist(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(BundlePlaylist_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct BundlePlaylistDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BundlePlaylistDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~BundlePlaylistDefaultTypeInternal() {}
  union {
    BundlePlaylist _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BundlePlaylistDefaultTypeInternal _BundlePlaylist_default_instance_;

inline constexpr BundleGuide::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        def_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR BundleGuide::BundleGuide(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(BundleGuide_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct BundleGuideDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BundleGuideDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~BundleGuideDefaultTypeInternal() {}
  union {
    BundleGuide _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BundleGuideDefaultTypeInternal _BundleGuide_default_instance_;

inline constexpr BundleScenario::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        def_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR BundleScenario::BundleScenario(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(BundleScenario_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct BundleScenarioDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BundleScenarioDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~BundleScenarioDefaultTypeInternal() {}
  union {
    BundleScenario _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BundleScenarioDefaultTypeInternal _BundleScenario_default_instance_;

inline constexpr BundleFile::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        scenarios_{},
        playlists_{},
        guides_{} {}

template <typename>
PROTOBUF_CONSTEXPR BundleFile::BundleFile(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(BundleFile_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct BundleFileDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BundleFileDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~BundleFileDefaultTypeInternal() {}
  union {
    BundleFile _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BundleFileDefaultTypeInternal _BundleFile_default_instance_;
}  // namespace aim
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_bundle_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_bundle_2eproto = nullptr;
const ::uint32_t
    TableStruct_bundle_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::aim::BundleScenario, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::aim::BundleScenario, _impl_.name_),
        PROTOBUF_FIELD_OFFSET(::aim::BundleScenario, _impl_.def_),
        0,
        1,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::aim::BundlePlaylist, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::aim::BundlePlaylist, _impl_.name_),
        PROTOBUF_FIELD_OFFSET(::aim::BundlePlaylist, _impl_.def_),
        0,
        1,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::aim::BundleGuide, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::aim::BundleGuide, _impl_.name_),
        PROTOBUF_FIELD_OFFSET(::aim::BundleGuide, _impl_.def_),
        0,
        1,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::aim::BundleFile, _impl_._has_bits_),
        6, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::aim::BundleFile, _impl_.scenarios_),
        PROTOBUF_FIELD_OFFSET(::aim::BundleFile, _impl_.playlists_),
        PROTOBUF_FIELD_OFFSET(::aim::BundleFile, _impl_.guides_),
        0,
        1,
        2,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::aim::BundleInfo, _impl_._has_bits_),
        6, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::aim::BundleInfo, _impl_.bundle_name_),
        PROTOBUF_FIELD_OFFSET(::aim::BundleInfo, _impl_.readonly_),
        PROTOBUF_FIELD_OFFSET(::aim::BundleInfo, _impl_.archived_),
        0,
        1,
        2,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::aim::BundleInfoFile, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::aim::BundleInfoFile, _impl_.bundles_),
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::aim::BundleScenario)},
        {7, sizeof(::aim::BundlePlaylist)},
        {14, sizeof(::aim::BundleGuide)},
        {21, sizeof(::aim::BundleFile)},
        {30, sizeof(::aim::BundleInfo)},
        {39, sizeof(::aim::BundleInfoFile)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::aim::_BundleScenario_default_instance_._instance,
    &::aim::_BundlePlaylist_default_instance_._instance,
    &::aim::_BundleGuide_default_instance_._instance,
    &::aim::_BundleFile_default_instance_._instance,
    &::aim::_BundleInfo_default_instance_._instance,
    &::aim::_BundleInfoFile_default_instance_._instance,
};
const char descriptor_table_protodef_bundle_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\014bundle.proto\022\003aim\032\016scenario.proto\032\016pla"
    "ylist.proto\032\013guide.proto\"=\n\016BundleScenar"
    "io\022\014\n\004name\030\001 \001(\t\022\035\n\003def\030\002 \001(\0132\020.aim.Scen"
    "arioDef\"=\n\016BundlePlaylist\022\014\n\004name\030\001 \001(\t\022"
    "\035\n\003def\030\002 \001(\0132\020.aim.PlaylistDef\"7\n\013Bundle"
    "Guide\022\014\n\004name\030\001 \001(\t\022\032\n\003def\030\002 \001(\0132\r.aim.G"
    "uideDef\"~\n\nBundleFile\022&\n\tscenarios\030\001 \003(\013"
    "2\023.aim.BundleScenario\022&\n\tplaylists\030\002 \003(\013"
    "2\023.aim.BundlePlaylist\022 \n\006guides\030\003 \003(\0132\020."
    "aim.BundleGuide\"E\n\nBundleInfo\022\023\n\013bundle_"
    "name\030\001 \001(\t\022\020\n\010readonly\030\002 \001(\010\022\020\n\010archived"
    "\030\003 \001(\010\"2\n\016BundleInfoFile\022 \n\007bundles\030\001 \003("
    "\0132\017.aim.BundleInfob\010editionsp\350\007"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_bundle_2eproto_deps[3] = {
        &::descriptor_table_guide_2eproto,
        &::descriptor_table_playlist_2eproto,
        &::descriptor_table_scenario_2eproto,
};
static ::absl::once_flag descriptor_table_bundle_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_bundle_2eproto = {
    false,
    false,
    511,
    descriptor_table_protodef_bundle_2eproto,
    "bundle.proto",
    &descriptor_table_bundle_2eproto_once,
    descriptor_table_bundle_2eproto_deps,
    3,
    6,
    schemas,
    file_default_instances,
    TableStruct_bundle_2eproto::offsets,
    file_level_enum_descriptors_bundle_2eproto,
    file_level_service_descriptors_bundle_2eproto,
};
namespace aim {
// ===================================================================

class BundleScenario::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<BundleScenario>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(BundleScenario, _impl_._has_bits_);
};

void BundleScenario::clear_def() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.def_ != nullptr) _impl_.def_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
BundleScenario::BundleScenario(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, BundleScenario_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:aim.BundleScenario)
}
PROTOBUF_NDEBUG_INLINE BundleScenario::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::aim::BundleScenario& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        name_(arena, from.name_) {}

BundleScenario::BundleScenario(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const BundleScenario& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, BundleScenario_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  BundleScenario* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.def_ = (CheckHasBit(cached_has_bits, 0x00000002U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.def_)
                : nullptr;

  // @@protoc_insertion_point(copy_constructor:aim.BundleScenario)
}
PROTOBUF_NDEBUG_INLINE BundleScenario::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        name_(arena) {}

inline void BundleScenario::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.def_ = {};
}
BundleScenario::~BundleScenario() {
  // @@protoc_insertion_point(destructor:aim.BundleScenario)
  SharedDtor(*this);
}
inline void BundleScenario::SharedDtor(MessageLite& self) {
  BundleScenario& this_ = static_cast<BundleScenario&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.name_.Destroy();
  delete this_._impl_.def_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL BundleScenario::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) BundleScenario(arena);
}
constexpr auto BundleScenario::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(BundleScenario),
                                            alignof(BundleScenario));
}
constexpr auto BundleScenario::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_BundleScenario_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &BundleScenario::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<BundleScenario>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &BundleScenario::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<BundleScenario>(), &BundleScenario::ByteSizeLong,
              &BundleScenario::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(BundleScenario, _impl_._cached_size_),
          false,
      },
      &BundleScenario::kDescriptorMethods,
      &descriptor_table_bundle_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull BundleScenario_class_data_ =
        BundleScenario::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
BundleScenario::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&BundleScenario_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(BundleScenario_class_data_.tc_table);
  return BundleScenario_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 31, 2>
BundleScenario::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(BundleScenario, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    BundleScenario_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::aim::BundleScenario>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .aim.ScenarioDef def = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 1, 0,
      PROTOBUF_FIELD_OFFSET(BundleScenario, _impl_.def_)}},
    // string name = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(BundleScenario, _impl_.name_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string name = 1;
    {PROTOBUF_FIELD_OFFSET(BundleScenario, _impl_.name_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // .aim.ScenarioDef def = 2;
    {PROTOBUF_FIELD_OFFSET(BundleScenario, _impl_.def_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::aim::ScenarioDef>()},
  }},
  {{
    "\22\4\0\0\0\0\0\0"
    "aim.BundleScenario"
    "name"
  }},
};
PROTOBUF_NOINLINE void BundleScenario::Clear() {
// @@protoc_insertion_point(message_clear_start:aim.BundleScenario)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.name_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      ABSL_DCHECK(_impl_.def_ != nullptr);
      _impl_.def_->Clear();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL BundleScenario::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const BundleScenario& this_ = static_cast<const BundleScenario&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL BundleScenario::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const BundleScenario& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:aim.BundleScenario)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string name = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    const ::std::string& _s = this_._internal_name();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "aim.BundleScenario.name");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // .aim.ScenarioDef def = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        2, *this_._impl_.def_, this_._impl_.def_->GetCachedSize(), target,
        stream);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:aim.BundleScenario)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t BundleScenario::ByteSizeLong(const MessageLite& base) {
  const BundleScenario& this_ = static_cast<const BundleScenario&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t BundleScenario::ByteSizeLong() const {
  const BundleScenario& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:aim.BundleScenario)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // string name = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_name());
    }
    // .aim.ScenarioDef def = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.def_);
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void BundleScenario::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<BundleScenario*>(&to_msg);
  auto& from = static_cast<const BundleScenario&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:aim.BundleScenario)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _this->_internal_set_name(from._internal_name());
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      ABSL_DCHECK(from._impl_.def_ != nullptr);
      if (_this->_impl_.def_ == nullptr) {
        _this->_impl_.def_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.def_);
      } else {
        _this->_impl_.def_->MergeFrom(*from._impl_.def_);
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void BundleScenario::CopyFrom(const BundleScenario& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:aim.BundleScenario)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void BundleScenario::InternalSwap(BundleScenario* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, &other->_impl_.name_, arena);
  swap(_impl_.def_, other->_impl_.def_);
}

::google::protobuf::Metadata BundleScenario::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class BundlePlaylist::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<BundlePlaylist>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(BundlePlaylist, _impl_._has_bits_);
};

void BundlePlaylist::clear_def() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.def_ != nullptr) _impl_.def_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
BundlePlaylist::BundlePlaylist(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, BundlePlaylist_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:aim.BundlePlaylist)
}
PROTOBUF_NDEBUG_INLINE BundlePlaylist::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::aim::BundlePlaylist& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        name_(arena, from.name_) {}

BundlePlaylist::BundlePlaylist(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const BundlePlaylist& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, BundlePlaylist_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  BundlePlaylist* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.def_ = (CheckHasBit(cached_has_bits, 0x00000002U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.def_)
                : nullptr;

  // @@protoc_insertion_point(copy_constructor:aim.BundlePlaylist)
}
PROTOBUF_NDEBUG_INLINE BundlePlaylist::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        name_(arena) {}

inline void BundlePlaylist::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.def_ = {};
}
BundlePlaylist::~BundlePlaylist() {
  // @@protoc_insertion_point(destructor:aim.BundlePlaylist)
  SharedDtor(*this);
}
inline void BundlePlaylist::SharedDtor(MessageLite& self) {
  BundlePlaylist& this_ = static_cast<BundlePlaylist&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.name_.Destroy();
  delete this_._impl_.def_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL BundlePlaylist::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) BundlePlaylist(arena);
}
constexpr auto BundlePlaylist::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(BundlePlaylist),
                                            alignof(BundlePlaylist));
}
constexpr auto BundlePlaylist::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_BundlePlaylist_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &BundlePlaylist::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<BundlePlaylist>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &BundlePlaylist::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<BundlePlaylist>(), &BundlePlaylist::ByteSizeLong,
              &BundlePlaylist::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(BundlePlaylist, _impl_._cached_size_),
          false,
      },
      &BundlePlaylist::kDescriptorMethods,
      &descriptor_table_bundle_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull BundlePlaylist_class_data_ =
        BundlePlaylist::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
BundlePlaylist::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&BundlePlaylist_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(BundlePlaylist_class_data_.tc_table);
  return BundlePlaylist_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 31, 2>
BundlePlaylist::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(BundlePlaylist, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    BundlePlaylist_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::aim::BundlePlaylist>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .aim.PlaylistDef def = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 1, 0,
      PROTOBUF_FIELD_OFFSET(BundlePlaylist, _impl_.def_)}},
    // string name = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(BundlePlaylist, _impl_.name_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string name = 1;
    {PROTOBUF_FIELD_OFFSET(BundlePlaylist, _impl_.name_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // .aim.PlaylistDef def = 2;
    {PROTOBUF_FIELD_OFFSET(BundlePlaylist, _impl_.def_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::aim::PlaylistDef>()},
  }},
  {{
    "\22\4\0\0\0\0\0\0"
    "aim.BundlePlaylist"
    "name"
  }},
};
PROTOBUF_NOINLINE void BundlePlaylist::Clear() {
// @@protoc_insertion_point(message_clear_start:aim.BundlePlaylist)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.name_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      ABSL_DCHECK(_impl_.def_ != nullptr);
      _impl_.def_->Clear();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL BundlePlaylist::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const BundlePlaylist& this_ = static_cast<const BundlePlaylist&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL BundlePlaylist::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const BundlePlaylist& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:aim.BundlePlaylist)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string name = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    const ::std::string& _s = this_._internal_name();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "aim.BundlePlaylist.name");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // .aim.PlaylistDef def = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        2, *this_._impl_.def_, this_._impl_.def_->GetCachedSize(), target,
        stream);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:aim.BundlePlaylist)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t BundlePlaylist::ByteSizeLong(const MessageLite& base) {
  const BundlePlaylist& this_ = static_cast<const BundlePlaylist&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t BundlePlaylist::ByteSizeLong() const {
  const BundlePlaylist& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:aim.BundlePlaylist)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // string name = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_name());
    }
    // .aim.PlaylistDef def = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.def_);
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void BundlePlaylist::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<BundlePlaylist*>(&to_msg);
  auto& from = static_cast<const BundlePlaylist&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:aim.BundlePlaylist)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _this->_internal_set_name(from._internal_name());
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      ABSL_DCHECK(from._impl_.def_ != nullptr);
      if (_this->_impl_.def_ == nullptr) {
        _this->_impl_.def_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.def_);
      } else {
        _this->_impl_.def_->MergeFrom(*from._impl_.def_);
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void BundlePlaylist::CopyFrom(const BundlePlaylist& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:aim.BundlePlaylist)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void BundlePlaylist::InternalSwap(BundlePlaylist* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, &other->_impl_.name_, arena);
  swap(_impl_.def_, other->_impl_.def_);
}

::google::protobuf::Metadata BundlePlaylist::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class BundleGuide::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<BundleGuide>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(BundleGuide, _impl_._has_bits_);
};

void BundleGuide::clear_def() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.def_ != nullptr) _impl_.def_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
BundleGuide::BundleGuide(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, BundleGuide_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:aim.BundleGuide)
}
PROTOBUF_NDEBUG_INLINE BundleGuide::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::aim::BundleGuide& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        name_(arena, from.name_) {}

BundleGuide::BundleGuide(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const BundleGuide& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, BundleGuide_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  BundleGuide* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.def_ = (CheckHasBit(cached_has_bits, 0x00000002U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.def_)
                : nullptr;

  // @@protoc_insertion_point(copy_constructor:aim.BundleGuide)
}
PROTOBUF_NDEBUG_INLINE BundleGuide::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        name_(arena) {}

inline void BundleGuide::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.def_ = {};
}
BundleGuide::~BundleGuide() {
  // @@protoc_insertion_point(destructor:aim.BundleGuide)
  SharedDtor(*this);
}
inline void BundleGuide::SharedDtor(MessageLite& self) {
  BundleGuide& this_ = static_cast<BundleGuide&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.name_.Destroy();
  delete this_._impl_.def_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL BundleGuide::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) BundleGuide(arena);
}
constexpr auto BundleGuide::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(BundleGuide),
                                            alignof(BundleGuide));
}
constexpr auto BundleGuide::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_BundleGuide_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &BundleGuide::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<BundleGuide>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &BundleGuide::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<BundleGuide>(), &BundleGuide::ByteSizeLong,
              &BundleGuide::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(BundleGuide, _impl_._cached_size_),
          false,
      },
      &BundleGuide::kDescriptorMethods,
      &descriptor_table_bundle_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull BundleGuide_class_data_ =
        BundleGuide::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
BundleGuide::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&BundleGuide_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(BundleGuide_class_data_.tc_table);
  return BundleGuide_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 28, 2>
BundleGuide::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(BundleGuide, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    BundleGuide_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::aim::BundleGuide>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .aim.GuideDef def = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 1, 0,
      PROTOBUF_FIELD_OFFSET(BundleGuide, _impl_.def_)}},
    // string name = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(BundleGuide, _impl_.name_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string name = 1;
    {PROTOBUF_FIELD_OFFSET(BundleGuide, _impl_.name_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // .aim.GuideDef def = 2;
    {PROTOBUF_FIELD_OFFSET(BundleGuide, _impl_.def_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::aim::GuideDef>()},
  }},
  {{
    "\17\4\0\0\0\0\0\0"
    "aim.BundleGuide"
    "name"
  }},
};
PROTOBUF_NOINLINE void BundleGuide::Clear() {
// @@protoc_insertion_point(message_clear_start:aim.BundleGuide)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.name_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      ABSL_DCHECK(_impl_.def_ != nullptr);
      _impl_.def_->Clear();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL BundleGuide::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const BundleGuide& this_ = static_cast<const BundleGuide&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL BundleGuide::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const BundleGuide& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:aim.BundleGuide)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string name = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    const ::std::string& _s = this_._internal_name();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "aim.BundleGuide.name");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // .aim.GuideDef def = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        2, *this_._impl_.def_, this_._impl_.def_->GetCachedSize(), target,
        stream);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:aim.BundleGuide)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t BundleGuide::ByteSizeLong(const MessageLite& base) {
  const BundleGuide& this_ = static_cast<const BundleGuide&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t BundleGuide::ByteSizeLong() const {
  const BundleGuide& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:aim.BundleGuide)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // string name = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_name());
    }
    // .aim.GuideDef def = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.def_);
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void BundleGuide::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<BundleGuide*>(&to_msg);
  auto& from = static_cast<const BundleGuide&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:aim.BundleGuide)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _this->_internal_set_name(from._internal_name());
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      ABSL_DCHECK(from._impl_.def_ != nullptr);
      if (_this->_impl_.def_ == nullptr) {
        _this->_impl_.def_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.def_);
      } else {
        _this->_impl_.def_->MergeFrom(*from._impl_.def_);
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void BundleGuide::CopyFrom(const BundleGuide& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:aim.BundleGuide)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void BundleGuide::InternalSwap(BundleGuide* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, &other->_impl_.name_, arena);
  swap(_impl_.def_, other->_impl_.def_);
}

::google::protobuf::Metadata BundleGuide::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class BundleFile::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<BundleFile>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(BundleFile, _impl_._has_bits_);
};

BundleFile::BundleFile(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, BundleFile_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:aim.BundleFile)
}
PROTOBUF_NDEBUG_INLINE BundleFile::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::aim::BundleFile& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        scenarios_{visibility, arena, from.scenarios_},
        playlists_{visibility, arena, from.playlists_},
        guides_{visibility, arena, from.guides_} {}

BundleFile::BundleFile(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const BundleFile& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, BundleFile_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  BundleFile* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:aim.BundleFile)
}
PROTOBUF_NDEBUG_INLINE BundleFile::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        scenarios_{visibility, arena},
        playlists_{visibility, arena},
        guides_{visibility, arena} {}

inline void BundleFile::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
BundleFile::~BundleFile() {
  // @@protoc_insertion_point(destructor:aim.BundleFile)
  SharedDtor(*this);
}
inline void BundleFile::SharedDtor(MessageLite& self) {
  BundleFile& this_ = static_cast<BundleFile&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL BundleFile::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) BundleFile(arena);
}
constexpr auto BundleFile::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(BundleFile, _impl_.scenarios_) +
          decltype(BundleFile::_impl_.scenarios_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(BundleFile, _impl_.playlists_) +
          decltype(BundleFile::_impl_.playlists_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(BundleFile, _impl_.guides_) +
          decltype(BundleFile::_impl_.guides_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(BundleFile), alignof(BundleFile), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&BundleFile::PlacementNew_,
                                 sizeof(BundleFile),
                                 alignof(BundleFile));
  }
}
constexpr auto BundleFile::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_BundleFile_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &BundleFile::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<BundleFile>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &BundleFile::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<BundleFile>(), &BundleFile::ByteSizeLong,
              &BundleFile::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(BundleFile, _impl_._cached_size_),
          false,
      },
      &BundleFile::kDescriptorMethods,
      &descriptor_table_bundle_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull BundleFile_class_data_ =
        BundleFile::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
BundleFile::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&BundleFile_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(BundleFile_class_data_.tc_table);
  return BundleFile_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 3, 0, 2>
BundleFile::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(BundleFile, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    3,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    BundleFile_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::aim::BundleFile>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // repeated .aim.BundleScenario scenarios = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(BundleFile, _impl_.scenarios_)}},
    // repeated .aim.BundlePlaylist playlists = 2;
    {::_pbi::TcParser::FastMtR1,
     {18, 1, 1,
      PROTOBUF_FIELD_OFFSET(BundleFile, _impl_.playlists_)}},
    // repeated .aim.BundleGuide guides = 3;
    {::_pbi::TcParser::FastMtR1,
     {26, 2, 2,
      PROTOBUF_FIELD_OFFSET(BundleFile, _impl_.guides_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .aim.BundleScenario scenarios = 1;
    {PROTOBUF_FIELD_OFFSET(BundleFile, _impl_.scenarios_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    // repeated .aim.BundlePlaylist playlists = 2;
    {PROTOBUF_FIELD_OFFSET(BundleFile, _impl_.playlists_), _Internal::kHasBitsOffset + 1, 1, (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    // repeated .aim.BundleGuide guides = 3;
    {PROTOBUF_FIELD_OFFSET(BundleFile, _impl_.guides_), _Internal::kHasBitsOffset + 2, 2, (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::aim::BundleScenario>()},
      {::_pbi::TcParser::GetTable<::aim::BundlePlaylist>()},
      {::_pbi::TcParser::GetTable<::aim::BundleGuide>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void BundleFile::Clear() {
// @@protoc_insertion_point(message_clear_start:aim.BundleFile)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      _impl_.scenarios_.Clear();
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
      _impl_.playlists_.Clear();
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000004U)) {
      _impl_.guides_.Clear();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL BundleFile::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const BundleFile& this_ = static_cast<const BundleFile&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL BundleFile::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const BundleFile& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:aim.BundleFile)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // repeated .aim.BundleScenario scenarios = 1;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    for (unsigned i = 0, n = static_cast<unsigned>(
                             this_._internal_scenarios_size());
         i < n; i++) {
      const auto& repfield = this_._internal_scenarios().Get(i);
      target =
          ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
              1, repfield, repfield.GetCachedSize(),
              target, stream);
    }
  }

  // repeated .aim.BundlePlaylist playlists = 2;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
    for (unsigned i = 0, n = static_cast<unsigned>(
                             this_._internal_playlists_size());
         i < n; i++) {
      const auto& repfield = this_._internal_playlists().Get(i);
      target =
          ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
              2, repfield, repfield.GetCachedSize(),
              target, stream);
    }
  }

  // repeated .aim.BundleGuide guides = 3;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000004U)) {
    for (unsigned i = 0, n = static_cast<unsigned>(
                             this_._internal_guides_size());
         i < n; i++) {
      const auto& repfield = this_._internal_guides().Get(i);
      target =
          ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
              3, repfield, repfield.GetCachedSize(),
              target, stream);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:aim.BundleFile)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t BundleFile::ByteSizeLong(const MessageLite& base) {
  const BundleFile& this_ = static_cast<const BundleFile&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t BundleFile::ByteSizeLong() const {
  const BundleFile& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:aim.BundleFile)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    // repeated .aim.BundleScenario scenarios = 1;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      total_size += 1UL * this_._internal_scenarios_size();
      for (const auto& msg : this_._internal_scenarios()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
    // repeated .aim.BundlePlaylist playlists = 2;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
      total_size += 1UL * this_._internal_playlists_size();
      for (const auto& msg : this_._internal_playlists()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
    // repeated .aim.BundleGuide guides = 3;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000004U)) {
      total_size += 1UL * this_._internal_guides_size();
      for (const auto& msg : this_._internal_guides()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void BundleFile::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<BundleFile*>(&to_msg);
  auto& from = static_cast<const BundleFile&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:aim.BundleFile)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      _this->_internal_mutable_scenarios()->InternalMergeFromWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), arena,
          from._internal_scenarios());
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
      _this->_internal_mutable_playlists()->InternalMergeFromWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), arena,
          from._internal_playlists());
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000004U)) {
      _this->_internal_mutable_guides()->InternalMergeFromWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), arena,
          from._internal_guides());
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void BundleFile::CopyFrom(const BundleFile& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:aim.BundleFile)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void BundleFile::InternalSwap(BundleFile* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.scenarios_.InternalSwap(&other->_impl_.scenarios_);
  _impl_.playlists_.InternalSwap(&other->_impl_.playlists_);
  _impl_.guides_.InternalSwap(&other->_impl_.guides_);
}

::google::protobuf::Metadata BundleFile::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class BundleInfo::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<BundleInfo>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(BundleInfo, _impl_._has_bits_);
};

BundleInfo::BundleInfo(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, BundleInfo_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:aim.BundleInfo)
}
PROTOBUF_NDEBUG_INLINE BundleInfo::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::aim::BundleInfo& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        bundle_name_(arena, from.bundle_name_) {}

BundleInfo::BundleInfo(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const BundleInfo& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, BundleInfo_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  BundleInfo* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, readonly_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, readonly_),
           offsetof(Impl_, archived_) -
               offsetof(Impl_, readonly_) +
               sizeof(Impl_::archived_));

  // @@protoc_insertion_point(copy_constructor:aim.BundleInfo)
}
PROTOBUF_NDEBUG_INLINE BundleInfo::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        bundle_name_(arena) {}

inline void BundleInfo::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, readonly_),
           0,
           offsetof(Impl_, archived_) -
               offsetof(Impl_, readonly_) +
               sizeof(Impl_::archived_));
}
BundleInfo::~BundleInfo() {
  // @@protoc_insertion_point(destructor:aim.BundleInfo)
  SharedDtor(*this);
}
inline void BundleInfo::SharedDtor(MessageLite& self) {
  BundleInfo& this_ = static_cast<BundleInfo&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.bundle_name_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL BundleInfo::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) BundleInfo(arena);
}
constexpr auto BundleInfo::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(BundleInfo),
                                            alignof(BundleInfo));
}
constexpr auto BundleInfo::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_BundleInfo_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &BundleInfo::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<BundleInfo>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &BundleInfo::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<BundleInfo>(), &BundleInfo::ByteSizeLong,
              &BundleInfo::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(BundleInfo, _impl_._cached_size_),
          false,
      },
      &BundleInfo::kDescriptorMethods,
      &descriptor_table_bundle_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull BundleInfo_class_data_ =
        BundleInfo::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
BundleInfo::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&BundleInfo_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(BundleInfo_class_data_.tc_table);
  return BundleInfo_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 34, 2>
BundleInfo::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(BundleInfo, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    BundleInfo_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::aim::BundleInfo>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string bundle_name = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(BundleInfo, _impl_.bundle_name_)}},
    // bool readonly = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(BundleInfo, _impl_.readonly_), 1>(),
     {16, 1, 0,
      PROTOBUF_FIELD_OFFSET(BundleInfo, _impl_.readonly_)}},
    // bool archived = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(BundleInfo, _impl_.archived_), 2>(),
     {24, 2, 0,
      PROTOBUF_FIELD_OFFSET(BundleInfo, _impl_.archived_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string bundle_name = 1;
    {PROTOBUF_FIELD_OFFSET(BundleInfo, _impl_.bundle_name_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // bool readonly = 2;
    {PROTOBUF_FIELD_OFFSET(BundleInfo, _impl_.readonly_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // bool archived = 3;
    {PROTOBUF_FIELD_OFFSET(BundleInfo, _impl_.archived_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
    "\16\13\0\0\0\0\0\0"
    "aim.BundleInfo"
    "bundle_name"
  }},
};
PROTOBUF_NOINLINE void BundleInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:aim.BundleInfo)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _impl_.bundle_name_.ClearNonDefaultToEmpty();
  }
  ::memset(&_impl_.readonly_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.archived_) -
      reinterpret_cast<char*>(&_impl_.readonly_)) + sizeof(_impl_.archived_));
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL BundleInfo::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const BundleInfo& this_ = static_cast<const BundleInfo&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL BundleInfo::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const BundleInfo& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:aim.BundleInfo)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string bundle_name = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    const ::std::string& _s = this_._internal_bundle_name();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "aim.BundleInfo.bundle_name");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // bool readonly = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        2, this_._internal_readonly(), target);
  }

  // bool archived = 3;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        3, this_._internal_archived(), target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:aim.BundleInfo)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t BundleInfo::ByteSizeLong(const MessageLite& base) {
  const BundleInfo& this_ = static_cast<const BundleInfo&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t BundleInfo::ByteSizeLong() const {
  const BundleInfo& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:aim.BundleInfo)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  total_size += ::absl::popcount(0x00000006U & cached_has_bits) * 2;
   {
    // string bundle_name = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_bundle_name());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void BundleInfo::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<BundleInfo*>(&to_msg);
  auto& from = static_cast<const BundleInfo&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:aim.BundleInfo)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _this->_internal_set_bundle_name(from._internal_bundle_name());
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _this->_impl_.readonly_ = from._impl_.readonly_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _this->_impl_.archived_ = from._impl_.archived_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void BundleInfo::CopyFrom(const BundleInfo& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:aim.BundleInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void BundleInfo::InternalSwap(BundleInfo* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.bundle_name_, &other->_impl_.bundle_name_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(BundleInfo, _impl_.archived_)
      + sizeof(BundleInfo::_impl_.archived_)
      - PROTOBUF_FIELD_OFFSET(BundleInfo, _impl_.readonly_)>(
          reinterpret_cast<char*>(&_impl_.readonly_),
          reinterpret_cast<char*>(&other->_impl_.readonly_));
}

::google::protobuf::Metadata BundleInfo::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class BundleInfoFile::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<BundleInfoFile>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(BundleInfoFile, _impl_._has_bits_);
};

BundleInfoFile::BundleInfoFile(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, BundleInfoFile_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:aim.BundleInfoFile)
}
PROTOBUF_NDEBUG_INLINE BundleInfoFile::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::aim::BundleInfoFile& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        bundles_{visibility, arena, from.bundles_} {}

BundleInfoFile::BundleInfoFile(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const BundleInfoFile& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, BundleInfoFile_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  BundleInfoFile* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:aim.BundleInfoFile)
}
PROTOBUF_NDEBUG_INLINE BundleInfoFile::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        bundles_{visibility, arena} {}

inline void BundleInfoFile::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
BundleInfoFile::~BundleInfoFile() {
  // @@protoc_insertion_point(destructor:aim.BundleInfoFile)
  SharedDtor(*this);
}
inline void BundleInfoFile::SharedDtor(MessageLite& self) {
  BundleInfoFile& this_ = static_cast<BundleInfoFile&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL BundleInfoFile::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) BundleInfoFile(arena);
}
constexpr auto BundleInfoFile::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(BundleInfoFile, _impl_.bundles_) +
          decltype(BundleInfoFile::_impl_.bundles_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(BundleInfoFile), alignof(BundleInfoFile), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&BundleInfoFile::PlacementNew_,
                                 sizeof(BundleInfoFile),
                                 alignof(BundleInfoFile));
  }
}
constexpr auto BundleInfoFile::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_BundleInfoFile_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &BundleInfoFile::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<BundleInfoFile>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &BundleInfoFile::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<BundleInfoFile>(), &BundleInfoFile::ByteSizeLong,
              &BundleInfoFile::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(BundleInfoFile, _impl_._cached_size_),
          false,
      },
      &BundleInfoFile::kDescriptorMethods,
      &descriptor_table_bundle_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull BundleInfoFile_class_data_ =
        BundleInfoFile::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
BundleInfoFile::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&BundleInfoFile_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(BundleInfoFile_class_data_.tc_table);
  return BundleInfoFile_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2>
BundleInfoFile::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(BundleInfoFile, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    BundleInfoFile_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::aim::BundleInfoFile>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .aim.BundleInfo bundles = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(BundleInfoFile, _impl_.bundles_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .aim.BundleInfo bundles = 1;
    {PROTOBUF_FIELD_OFFSET(BundleInfoFile, _impl_.bundles_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::aim::BundleInfo>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void BundleInfoFile::Clear() {
// @@protoc_insertion_point(message_clear_start:aim.BundleInfoFile)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    _impl_.bundles_.Clear();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL BundleInfoFile::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const BundleInfoFile& this_ = static_cast<const BundleInfoFile&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL BundleInfoFile::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const BundleInfoFile& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:aim.BundleInfoFile)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // repeated .aim.BundleInfo bundles = 1;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    for (unsigned i = 0, n = static_cast<unsigned>(
                             this_._internal_bundles_size());
         i < n; i++) {
      const auto& repfield = this_._internal_bundles().Get(i);
      target =
          ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
              1, repfield, repfield.GetCachedSize(),
              target, stream);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:aim.BundleInfoFile)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t BundleInfoFile::ByteSizeLong(const MessageLite& base) {
  const BundleInfoFile& this_ = static_cast<const BundleInfoFile&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t BundleInfoFile::ByteSizeLong() const {
  const BundleInfoFile& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:aim.BundleInfoFile)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
   {
    // repeated .aim.BundleInfo bundles = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      total_size += 1UL * this_._internal_bundles_size();
      for (const auto& msg : this_._internal_bundles()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void BundleInfoFile::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<BundleInfoFile*>(&to_msg);
  auto& from = static_cast<const BundleInfoFile&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:aim.BundleInfoFile)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    _this->_internal_mutable_bundles()->InternalMergeFromWithArena(
        ::google::protobuf::MessageLite::internal_visibility(), arena,
        from._internal_bundles());
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void BundleInfoFile::CopyFrom(const BundleInfoFile& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:aim.BundleInfoFile)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void BundleInfoFile::InternalSwap(BundleInfoFile* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.bundles_.InternalSwap(&other->_impl_.bundles_);
}

::google::protobuf::Metadata BundleInfoFile::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace aim
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_bundle_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
