// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bundle.proto
// Protobuf C++ Version: 6.33.5

#ifndef bundle_2eproto_2epb_2eh
#define bundle_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033005
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "scenario.pb.h"
#include "playlist.pb.h"
#include "guide.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_bundle_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_bundle_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_bundle_2eproto;
}  // extern "C"
namespace aim {
class BundleFile;
struct BundleFileDefaultTypeInternal;
extern BundleFileDefaultTypeInternal _BundleFile_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull BundleFile_class_data_;
class BundleGuide;
struct BundleGuideDefaultTypeInternal;
extern BundleGuideDefaultTypeInternal _BundleGuide_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull BundleGuide_class_data_;
class BundleInfo;
struct BundleInfoDefaultTypeInternal;
extern BundleInfoDefaultTypeInternal _BundleInfo_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull BundleInfo_class_data_;
class BundleInfoFile;
struct BundleInfoFileDefaultTypeInternal;
extern BundleInfoFileDefaultTypeInternal _BundleInfoFile_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull BundleInfoFile_class_data_;
class BundlePlaylist;
struct BundlePlaylistDefaultTypeInternal;
extern BundlePlaylistDefaultTypeInternal _BundlePlaylist_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull BundlePlaylist_class_data_;
class BundleScenario;
struct BundleScenarioDefaultTypeInternal;
extern BundleScenarioDefaultTypeInternal _BundleScenario_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull BundleScenario_class_data_;
}  // namespace aim
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace aim {

// ===================================================================


// -------------------------------------------------------------------

class BundleInfo final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:aim.BundleInfo) */ {
 public:
  inline BundleInfo() : BundleInfo(nullptr) {}
  ~BundleInfo() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(BundleInfo* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(BundleInfo));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR BundleInfo(::google::protobuf::internal::ConstantInitialized);

  inline BundleInfo(const BundleInfo& from) : BundleInfo(nullptr, from) {}
  inline BundleInfo(BundleInfo&& from) noexcept
      : BundleInfo(nullptr, ::std::move(from)) {}
  inline BundleInfo& operator=(const BundleInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline BundleInfo& operator=(BundleInfo&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BundleInfo& default_instance() {
    return *reinterpret_cast<const BundleInfo*>(
        &_BundleInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 4;
  friend void swap(BundleInfo& a, BundleInfo& b) { a.Swap(&b); }
  inline void Swap(BundleInfo* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BundleInfo* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BundleInfo* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<BundleInfo>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const BundleInfo& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const BundleInfo& from) { BundleInfo::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(BundleInfo* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "aim.BundleInfo"; }

  explicit BundleInfo(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  BundleInfo(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const BundleInfo& from);
  BundleInfo(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, BundleInfo&& from) noexcept
      : BundleInfo(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kBundleNameFieldNumber = 1,
    kReadonlyFieldNumber = 2,
    kArchivedFieldNumber = 3,
  };
  // string bundle_name = 1;
  bool has_bundle_name() const;
  void clear_bundle_name() ;
  const ::std::string& bundle_name() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_bundle_name(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_bundle_name();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_bundle_name();
  void set_allocated_bundle_name(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_bundle_name() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_bundle_name(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_bundle_name();

  public:
  // bool readonly = 2;
  bool has_readonly() const;
  void clear_readonly() ;
  bool readonly() const;
  void set_readonly(bool value);

  private:
  bool _internal_readonly() const;
  void _internal_set_readonly(bool value);

  public:
  // bool archived = 3;
  bool has_archived() const;
  void clear_archived() ;
  bool archived() const;
  void set_archived(bool value);

  private:
  bool _internal_archived() const;
  void _internal_set_archived(bool value);

  public:
  // @@protoc_insertion_point(class_scope:aim.BundleInfo)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   0, 34,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const BundleInfo& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr bundle_name_;
    bool readonly_;
    bool archived_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_bundle_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull BundleInfo_class_data_;
// -------------------------------------------------------------------

class BundleInfoFile final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:aim.BundleInfoFile) */ {
 public:
  inline BundleInfoFile() : BundleInfoFile(nullptr) {}
  ~BundleInfoFile() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(BundleInfoFile* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(BundleInfoFile));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR BundleInfoFile(::google::protobuf::internal::ConstantInitialized);

  inline BundleInfoFile(const BundleInfoFile& from) : BundleInfoFile(nullptr, from) {}
  inline BundleInfoFile(BundleInfoFile&& from) noexcept
      : BundleInfoFile(nullptr, ::std::move(from)) {}
  inline BundleInfoFile& operator=(const BundleInfoFile& from) {
    CopyFrom(from);
    return *this;
  }
  inline BundleInfoFile& operator=(BundleInfoFile&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BundleInfoFile& default_instance() {
    return *reinterpret_cast<const BundleInfoFile*>(
        &_BundleInfoFile_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 5;
  friend void swap(BundleInfoFile& a, BundleInfoFile& b) { a.Swap(&b); }
  inline void Swap(BundleInfoFile* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BundleInfoFile* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BundleInfoFile* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<BundleInfoFile>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const BundleInfoFile& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const BundleInfoFile& from) { BundleInfoFile::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(BundleInfoFile* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "aim.BundleInfoFile"; }

  explicit BundleInfoFile(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  BundleInfoFile(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const BundleInfoFile& from);
  BundleInfoFile(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, BundleInfoFile&& from) noexcept
      : BundleInfoFile(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kBundlesFieldNumber = 1,
  };
  // repeated .aim.BundleInfo bundles = 1;
  int bundles_size() const;
  private:
  int _internal_bundles_size() const;

  public:
  void clear_bundles() ;
  ::aim::BundleInfo* PROTOBUF_NONNULL mutable_bundles(int index);
  ::google::protobuf::RepeatedPtrField<::aim::BundleInfo>* PROTOBUF_NONNULL mutable_bundles();

  private:
  const ::google::protobuf::RepeatedPtrField<::aim::BundleInfo>& _internal_bundles() const;
  ::google::protobuf::RepeatedPtrField<::aim::BundleInfo>* PROTOBUF_NONNULL _internal_mutable_bundles();
  public:
  const ::aim::BundleInfo& bundles(int index) const;
  ::aim::BundleInfo* PROTOBUF_NONNULL add_bundles();
  const ::google::protobuf::RepeatedPtrField<::aim::BundleInfo>& bundles() const;
  // @@protoc_insertion_point(class_scope:aim.BundleInfoFile)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const BundleInfoFile& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::aim::BundleInfo > bundles_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_bundle_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull BundleInfoFile_class_data_;
// -------------------------------------------------------------------

class BundlePlaylist final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:aim.BundlePlaylist) */ {
 public:
  inline BundlePlaylist() : BundlePlaylist(nullptr) {}
  ~BundlePlaylist() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(BundlePlaylist* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(BundlePlaylist));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR BundlePlaylist(::google::protobuf::internal::ConstantInitialized);

  inline BundlePlaylist(const BundlePlaylist& from) : BundlePlaylist(nullptr, from) {}
  inline BundlePlaylist(BundlePlaylist&& from) noexcept
      : BundlePlaylist(nullptr, ::std::move(from)) {}
  inline BundlePlaylist& operator=(const BundlePlaylist& from) {
    CopyFrom(from);
    return *this;
  }
  inline BundlePlaylist& operator=(BundlePlaylist&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BundlePlaylist& default_instance() {
    return *reinterpret_cast<const BundlePlaylist*>(
        &_BundlePlaylist_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(BundlePlaylist& a, BundlePlaylist& b) { a.Swap(&b); }
  inline void Swap(BundlePlaylist* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BundlePlaylist* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BundlePlaylist* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<BundlePlaylist>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const BundlePlaylist& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const BundlePlaylist& from) { BundlePlaylist::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(BundlePlaylist* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "aim.BundlePlaylist"; }

  explicit BundlePlaylist(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  BundlePlaylist(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const BundlePlaylist& from);
  BundlePlaylist(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, BundlePlaylist&& from) noexcept
      : BundlePlaylist(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kNameFieldNumber = 1,
    kDefFieldNumber = 2,
  };
  // string name = 1;
  bool has_name() const;
  void clear_name() ;
  const ::std::string& name() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_name(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_name();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_name();
  void set_allocated_name(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_name() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_name(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_name();

  public:
  // .aim.PlaylistDef def = 2;
  bool has_def() const;
  void clear_def() ;
  const ::aim::PlaylistDef& def() const;
  [[nodiscard]] ::aim::PlaylistDef* PROTOBUF_NULLABLE release_def();
  ::aim::PlaylistDef* PROTOBUF_NONNULL mutable_def();
  void set_allocated_def(::aim::PlaylistDef* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_def(::aim::PlaylistDef* PROTOBUF_NULLABLE value);
  ::aim::PlaylistDef* PROTOBUF_NULLABLE unsafe_arena_release_def();

  private:
  const ::aim::PlaylistDef& _internal_def() const;
  ::aim::PlaylistDef* PROTOBUF_NONNULL _internal_mutable_def();

  public:
  // @@protoc_insertion_point(class_scope:aim.BundlePlaylist)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   1, 31,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const BundlePlaylist& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr name_;
    ::aim::PlaylistDef* PROTOBUF_NULLABLE def_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_bundle_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull BundlePlaylist_class_data_;
// -------------------------------------------------------------------

class BundleGuide final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:aim.BundleGuide) */ {
 public:
  inline BundleGuide() : BundleGuide(nullptr) {}
  ~BundleGuide() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(BundleGuide* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(BundleGuide));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR BundleGuide(::google::protobuf::internal::ConstantInitialized);

  inline BundleGuide(const BundleGuide& from) : BundleGuide(nullptr, from) {}
  inline BundleGuide(BundleGuide&& from) noexcept
      : BundleGuide(nullptr, ::std::move(from)) {}
  inline BundleGuide& operator=(const BundleGuide& from) {
    CopyFrom(from);
    return *this;
  }
  inline BundleGuide& operator=(BundleGuide&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BundleGuide& default_instance() {
    return *reinterpret_cast<const BundleGuide*>(
        &_BundleGuide_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(BundleGuide& a, BundleGuide& b) { a.Swap(&b); }
  inline void Swap(BundleGuide* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BundleGuide* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BundleGuide* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<BundleGuide>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const BundleGuide& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const BundleGuide& from) { BundleGuide::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(BundleGuide* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "aim.BundleGuide"; }

  explicit BundleGuide(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  BundleGuide(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const BundleGuide& from);
  BundleGuide(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, BundleGuide&& from) noexcept
      : BundleGuide(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kNameFieldNumber = 1,
    kDefFieldNumber = 2,
  };
  // string name = 1;
  bool has_name() const;
  void clear_name() ;
  const ::std::string& name() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_name(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_name();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_name();
  void set_allocated_name(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_name() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_name(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_name();

  public:
  // .aim.GuideDef def = 2;
  bool has_def() const;
  void clear_def() ;
  const ::aim::GuideDef& def() const;
  [[nodiscard]] ::aim::GuideDef* PROTOBUF_NULLABLE release_def();
  ::aim::GuideDef* PROTOBUF_NONNULL mutable_def();
  void set_allocated_def(::aim::GuideDef* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_def(::aim::GuideDef* PROTOBUF_NULLABLE value);
  ::aim::GuideDef* PROTOBUF_NULLABLE unsafe_arena_release_def();

  private:
  const ::aim::GuideDef& _internal_def() const;
  ::aim::GuideDef* PROTOBUF_NONNULL _internal_mutable_def();

  public:
  // @@protoc_insertion_point(class_scope:aim.BundleGuide)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   1, 28,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const BundleGuide& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr name_;
    ::aim::GuideDef* PROTOBUF_NULLABLE def_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_bundle_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull BundleGuide_class_data_;
// -------------------------------------------------------------------

class BundleScenario final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:aim.BundleScenario) */ {
 public:
  inline BundleScenario() : BundleScenario(nullptr) {}
  ~BundleScenario() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(BundleScenario* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(BundleScenario));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR BundleScenario(::google::protobuf::internal::ConstantInitialized);

  inline BundleScenario(const BundleScenario& from) : BundleScenario(nullptr, from) {}
  inline BundleScenario(BundleScenario&& from) noexcept
      : BundleScenario(nullptr, ::std::move(from)) {}
  inline BundleScenario& operator=(const BundleScenario& from) {
    CopyFrom(from);
    return *this;
  }
  inline BundleScenario& operator=(BundleScenario&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BundleScenario& default_instance() {
    return *reinterpret_cast<const BundleScenario*>(
        &_BundleScenario_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(BundleScenario& a, BundleScenario& b) { a.Swap(&b); }
  inline void Swap(BundleScenario* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BundleScenario* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BundleScenario* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<BundleScenario>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const BundleScenario& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const BundleScenario& from) { BundleScenario::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(BundleScenario* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "aim.BundleScenario"; }

  explicit BundleScenario(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  BundleScenario(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const BundleScenario& from);
  BundleScenario(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, BundleScenario&& from) noexcept
      : BundleScenario(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kNameFieldNumber = 1,
    kDefFieldNumber = 2,
  };
  // string name = 1;
  bool has_name() const;
  void clear_name() ;
  const ::std::string& name() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_name(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_name();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_name();
  void set_allocated_name(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_name() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_name(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_name();

  public:
  // .aim.ScenarioDef def = 2;
  bool has_def() const;
  void clear_def() ;
  const ::aim::ScenarioDef& def() const;
  [[nodiscard]] ::aim::ScenarioDef* PROTOBUF_NULLABLE release_def();
  ::aim::ScenarioDef* PROTOBUF_NONNULL mutable_def();
  void set_allocated_def(::aim::ScenarioDef* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_def(::aim::ScenarioDef* PROTOBUF_NULLABLE value);
  ::aim::ScenarioDef* PROTOBUF_NULLABLE unsafe_arena_release_def();

  private:
  const ::aim::ScenarioDef& _internal_def() const;
  ::aim::ScenarioDef* PROTOBUF_NONNULL _internal_mutable_def();

  public:
  // @@protoc_insertion_point(class_scope:aim.BundleScenario)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   1, 31,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const BundleScenario& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr name_;
    ::aim::ScenarioDef* PROTOBUF_NULLABLE def_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_bundle_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull BundleScenario_class_data_;
// -------------------------------------------------------------------

class BundleFile final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:aim.BundleFile) */ {
 public:
  inline BundleFile() : BundleFile(nullptr) {}
  ~BundleFile() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(BundleFile* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(BundleFile));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR BundleFile(::google::protobuf::internal::ConstantInitialized);

  inline BundleFile(const BundleFile& from) : BundleFile(nullptr, from) {}
  inline BundleFile(BundleFile&& from) noexcept
      : BundleFile(nullptr, ::std::move(from)) {}
  inline BundleFile& operator=(const BundleFile& from) {
    CopyFrom(from);
    return *this;
  }
  inline BundleFile& operator=(BundleFile&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BundleFile& default_instance() {
    return *reinterpret_cast<const BundleFile*>(
        &_BundleFile_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(BundleFile& a, BundleFile& b) { a.Swap(&b); }
  inline void Swap(BundleFile* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BundleFile* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BundleFile* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<BundleFile>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const BundleFile& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const BundleFile& from) { BundleFile::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(BundleFile* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "aim.BundleFile"; }

  explicit BundleFile(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  BundleFile(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const BundleFile& from);
  BundleFile(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, BundleFile&& from) noexcept
      : BundleFile(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kScenariosFieldNumber = 1,
    kPlaylistsFieldNumber = 2,
    kGuidesFieldNumber = 3,
  };
  // repeated .aim.BundleScenario scenarios = 1;
  int scenarios_size() const;
  private:
  int _internal_scenarios_size() const;

  public:
  void clear_scenarios() ;
  ::aim::BundleScenario* PROTOBUF_NONNULL mutable_scenarios(int index);
  ::google::protobuf::RepeatedPtrField<::aim::BundleScenario>* PROTOBUF_NONNULL mutable_scenarios();

  private:
  const ::google::protobuf::RepeatedPtrField<::aim::BundleScenario>& _internal_scenarios() const;
  ::google::protobuf::RepeatedPtrField<::aim::BundleScenario>* PROTOBUF_NONNULL _internal_mutable_scenarios();
  public:
  const ::aim::BundleScenario& scenarios(int index) const;
  ::aim::BundleScenario* PROTOBUF_NONNULL add_scenarios();
  const ::google::protobuf::RepeatedPtrField<::aim::BundleScenario>& scenarios() const;
  // repeated .aim.BundlePlaylist playlists = 2;
  int playlists_size() const;
  private:
  int _internal_playlists_size() const;

  public:
  void clear_playlists() ;
  ::aim::BundlePlaylist* PROTOBUF_NONNULL mutable_playlists(int index);
  ::google::protobuf::RepeatedPtrField<::aim::BundlePlaylist>* PROTOBUF_NONNULL mutable_playlists();

  private:
  const ::google::protobuf::RepeatedPtrField<::aim::BundlePlaylist>& _internal_playlists() const;
  ::google::protobuf::RepeatedPtrField<::aim::BundlePlaylist>* PROTOBUF_NONNULL _internal_mutable_playlists();
  public:
  const ::aim::BundlePlaylist& playlists(int index) const;
  ::aim::BundlePlaylist* PROTOBUF_NONNULL add_playlists();
  const ::google::protobuf::RepeatedPtrField<::aim::BundlePlaylist>& playlists() const;
  // repeated .aim.BundleGuide guides = 3;
  int guides_size() const;
  private:
  int _internal_guides_size() const;

  public:
  void clear_guides() ;
  ::aim::BundleGuide* PROTOBUF_NONNULL mutable_guides(int index);
  ::google::protobuf::RepeatedPtrField<::aim::BundleGuide>* PROTOBUF_NONNULL mutable_guides();

  private:
  const ::google::protobuf::RepeatedPtrField<::aim::BundleGuide>& _internal_guides() const;
  ::google::protobuf::RepeatedPtrField<::aim::BundleGuide>* PROTOBUF_NONNULL _internal_mutable_guides();
  public:
  const ::aim::BundleGuide& guides(int index) const;
  ::aim::BundleGuide* PROTOBUF_NONNULL add_guides();
  const ::google::protobuf::RepeatedPtrField<::aim::BundleGuide>& guides() const;
  // @@protoc_insertion_point(class_scope:aim.BundleFile)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   3, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const BundleFile& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::aim::BundleScenario > scenarios_;
    ::google::protobuf::RepeatedPtrField< ::aim::BundlePlaylist > playlists_;
    ::google::protobuf::RepeatedPtrField< ::aim::BundleGuide > guides_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_bundle_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull BundleFile_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// BundleScenario

// string name = 1;
inline bool BundleScenario::has_name() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  return value;
}
inline void BundleScenario::clear_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& BundleScenario::name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:aim.BundleScenario.name)
  return _internal_name();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void BundleScenario::set_name(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:aim.BundleScenario.name)
}
inline ::std::string* PROTOBUF_NONNULL BundleScenario::mutable_name()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:aim.BundleScenario.name)
  return _s;
}
inline const ::std::string& BundleScenario::_internal_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.name_.Get();
}
inline void BundleScenario::_internal_set_name(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL BundleScenario::_internal_mutable_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.name_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE BundleScenario::release_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:aim.BundleScenario.name)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.name_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.name_.Set("", GetArena());
  }
  return released;
}
inline void BundleScenario::set_allocated_name(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.name_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:aim.BundleScenario.name)
}

// .aim.ScenarioDef def = 2;
inline bool BundleScenario::has_def() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  PROTOBUF_ASSUME(!value || _impl_.def_ != nullptr);
  return value;
}
inline const ::aim::ScenarioDef& BundleScenario::_internal_def() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::aim::ScenarioDef* p = _impl_.def_;
  return p != nullptr ? *p : reinterpret_cast<const ::aim::ScenarioDef&>(::aim::_ScenarioDef_default_instance_);
}
inline const ::aim::ScenarioDef& BundleScenario::def() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:aim.BundleScenario.def)
  return _internal_def();
}
inline void BundleScenario::unsafe_arena_set_allocated_def(
    ::aim::ScenarioDef* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.def_);
  }
  _impl_.def_ = reinterpret_cast<::aim::ScenarioDef*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:aim.BundleScenario.def)
}
inline ::aim::ScenarioDef* PROTOBUF_NULLABLE BundleScenario::release_def() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::aim::ScenarioDef* released = _impl_.def_;
  _impl_.def_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::aim::ScenarioDef* PROTOBUF_NULLABLE BundleScenario::unsafe_arena_release_def() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:aim.BundleScenario.def)

  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::aim::ScenarioDef* temp = _impl_.def_;
  _impl_.def_ = nullptr;
  return temp;
}
inline ::aim::ScenarioDef* PROTOBUF_NONNULL BundleScenario::_internal_mutable_def() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.def_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::aim::ScenarioDef>(GetArena());
    _impl_.def_ = reinterpret_cast<::aim::ScenarioDef*>(p);
  }
  return _impl_.def_;
}
inline ::aim::ScenarioDef* PROTOBUF_NONNULL BundleScenario::mutable_def()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::aim::ScenarioDef* _msg = _internal_mutable_def();
  // @@protoc_insertion_point(field_mutable:aim.BundleScenario.def)
  return _msg;
}
inline void BundleScenario::set_allocated_def(::aim::ScenarioDef* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.def_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }

  _impl_.def_ = reinterpret_cast<::aim::ScenarioDef*>(value);
  // @@protoc_insertion_point(field_set_allocated:aim.BundleScenario.def)
}

// -------------------------------------------------------------------

// BundlePlaylist

// string name = 1;
inline bool BundlePlaylist::has_name() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  return value;
}
inline void BundlePlaylist::clear_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& BundlePlaylist::name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:aim.BundlePlaylist.name)
  return _internal_name();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void BundlePlaylist::set_name(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:aim.BundlePlaylist.name)
}
inline ::std::string* PROTOBUF_NONNULL BundlePlaylist::mutable_name()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:aim.BundlePlaylist.name)
  return _s;
}
inline const ::std::string& BundlePlaylist::_internal_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.name_.Get();
}
inline void BundlePlaylist::_internal_set_name(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL BundlePlaylist::_internal_mutable_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.name_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE BundlePlaylist::release_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:aim.BundlePlaylist.name)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.name_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.name_.Set("", GetArena());
  }
  return released;
}
inline void BundlePlaylist::set_allocated_name(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.name_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:aim.BundlePlaylist.name)
}

// .aim.PlaylistDef def = 2;
inline bool BundlePlaylist::has_def() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  PROTOBUF_ASSUME(!value || _impl_.def_ != nullptr);
  return value;
}
inline const ::aim::PlaylistDef& BundlePlaylist::_internal_def() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::aim::PlaylistDef* p = _impl_.def_;
  return p != nullptr ? *p : reinterpret_cast<const ::aim::PlaylistDef&>(::aim::_PlaylistDef_default_instance_);
}
inline const ::aim::PlaylistDef& BundlePlaylist::def() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:aim.BundlePlaylist.def)
  return _internal_def();
}
inline void BundlePlaylist::unsafe_arena_set_allocated_def(
    ::aim::PlaylistDef* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.def_);
  }
  _impl_.def_ = reinterpret_cast<::aim::PlaylistDef*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:aim.BundlePlaylist.def)
}
inline ::aim::PlaylistDef* PROTOBUF_NULLABLE BundlePlaylist::release_def() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::aim::PlaylistDef* released = _impl_.def_;
  _impl_.def_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::aim::PlaylistDef* PROTOBUF_NULLABLE BundlePlaylist::unsafe_arena_release_def() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:aim.BundlePlaylist.def)

  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::aim::PlaylistDef* temp = _impl_.def_;
  _impl_.def_ = nullptr;
  return temp;
}
inline ::aim::PlaylistDef* PROTOBUF_NONNULL BundlePlaylist::_internal_mutable_def() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.def_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::aim::PlaylistDef>(GetArena());
    _impl_.def_ = reinterpret_cast<::aim::PlaylistDef*>(p);
  }
  return _impl_.def_;
}
inline ::aim::PlaylistDef* PROTOBUF_NONNULL BundlePlaylist::mutable_def()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::aim::PlaylistDef* _msg = _internal_mutable_def();
  // @@protoc_insertion_point(field_mutable:aim.BundlePlaylist.def)
  return _msg;
}
inline void BundlePlaylist::set_allocated_def(::aim::PlaylistDef* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.def_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }

  _impl_.def_ = reinterpret_cast<::aim::PlaylistDef*>(value);
  // @@protoc_insertion_point(field_set_allocated:aim.BundlePlaylist.def)
}

// -------------------------------------------------------------------

// BundleGuide

// string name = 1;
inline bool BundleGuide::has_name() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  return value;
}
inline void BundleGuide::clear_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& BundleGuide::name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:aim.BundleGuide.name)
  return _internal_name();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void BundleGuide::set_name(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:aim.BundleGuide.name)
}
inline ::std::string* PROTOBUF_NONNULL BundleGuide::mutable_name()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:aim.BundleGuide.name)
  return _s;
}
inline const ::std::string& BundleGuide::_internal_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.name_.Get();
}
inline void BundleGuide::_internal_set_name(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL BundleGuide::_internal_mutable_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.name_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE BundleGuide::release_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:aim.BundleGuide.name)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.name_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.name_.Set("", GetArena());
  }
  return released;
}
inline void BundleGuide::set_allocated_name(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.name_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:aim.BundleGuide.name)
}

// .aim.GuideDef def = 2;
inline bool BundleGuide::has_def() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  PROTOBUF_ASSUME(!value || _impl_.def_ != nullptr);
  return value;
}
inline const ::aim::GuideDef& BundleGuide::_internal_def() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::aim::GuideDef* p = _impl_.def_;
  return p != nullptr ? *p : reinterpret_cast<const ::aim::GuideDef&>(::aim::_GuideDef_default_instance_);
}
inline const ::aim::GuideDef& BundleGuide::def() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:aim.BundleGuide.def)
  return _internal_def();
}
inline void BundleGuide::unsafe_arena_set_allocated_def(
    ::aim::GuideDef* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.def_);
  }
  _impl_.def_ = reinterpret_cast<::aim::GuideDef*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:aim.BundleGuide.def)
}
inline ::aim::GuideDef* PROTOBUF_NULLABLE BundleGuide::release_def() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::aim::GuideDef* released = _impl_.def_;
  _impl_.def_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::aim::GuideDef* PROTOBUF_NULLABLE BundleGuide::unsafe_arena_release_def() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:aim.BundleGuide.def)

  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::aim::GuideDef* temp = _impl_.def_;
  _impl_.def_ = nullptr;
  return temp;
}
inline ::aim::GuideDef* PROTOBUF_NONNULL BundleGuide::_internal_mutable_def() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.def_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::aim::GuideDef>(GetArena());
    _impl_.def_ = reinterpret_cast<::aim::GuideDef*>(p);
  }
  return _impl_.def_;
}
inline ::aim::GuideDef* PROTOBUF_NONNULL BundleGuide::mutable_def()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::aim::GuideDef* _msg = _internal_mutable_def();
  // @@protoc_insertion_point(field_mutable:aim.BundleGuide.def)
  return _msg;
}
inline void BundleGuide::set_allocated_def(::aim::GuideDef* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.def_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }

  _impl_.def_ = reinterpret_cast<::aim::GuideDef*>(value);
  // @@protoc_insertion_point(field_set_allocated:aim.BundleGuide.def)
}

// -------------------------------------------------------------------

// BundleFile

// repeated .aim.BundleScenario scenarios = 1;
inline int BundleFile::_internal_scenarios_size() const {
  return _internal_scenarios().size();
}
inline int BundleFile::scenarios_size() const {
  return _internal_scenarios_size();
}
inline void BundleFile::clear_scenarios() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.scenarios_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::aim::BundleScenario* PROTOBUF_NONNULL BundleFile::mutable_scenarios(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:aim.BundleFile.scenarios)
  return _internal_mutable_scenarios()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::aim::BundleScenario>* PROTOBUF_NONNULL BundleFile::mutable_scenarios()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:aim.BundleFile.scenarios)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_scenarios();
}
inline const ::aim::BundleScenario& BundleFile::scenarios(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:aim.BundleFile.scenarios)
  return _internal_scenarios().Get(index);
}
inline ::aim::BundleScenario* PROTOBUF_NONNULL BundleFile::add_scenarios()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::aim::BundleScenario* _add =
      _internal_mutable_scenarios()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:aim.BundleFile.scenarios)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::aim::BundleScenario>& BundleFile::scenarios() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:aim.BundleFile.scenarios)
  return _internal_scenarios();
}
inline const ::google::protobuf::RepeatedPtrField<::aim::BundleScenario>&
BundleFile::_internal_scenarios() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.scenarios_;
}
inline ::google::protobuf::RepeatedPtrField<::aim::BundleScenario>* PROTOBUF_NONNULL
BundleFile::_internal_mutable_scenarios() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.scenarios_;
}

// repeated .aim.BundlePlaylist playlists = 2;
inline int BundleFile::_internal_playlists_size() const {
  return _internal_playlists().size();
}
inline int BundleFile::playlists_size() const {
  return _internal_playlists_size();
}
inline void BundleFile::clear_playlists() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.playlists_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::aim::BundlePlaylist* PROTOBUF_NONNULL BundleFile::mutable_playlists(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:aim.BundleFile.playlists)
  return _internal_mutable_playlists()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::aim::BundlePlaylist>* PROTOBUF_NONNULL BundleFile::mutable_playlists()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_mutable_list:aim.BundleFile.playlists)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_playlists();
}
inline const ::aim::BundlePlaylist& BundleFile::playlists(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:aim.BundleFile.playlists)
  return _internal_playlists().Get(index);
}
inline ::aim::BundlePlaylist* PROTOBUF_NONNULL BundleFile::add_playlists()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::aim::BundlePlaylist* _add =
      _internal_mutable_playlists()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_add:aim.BundleFile.playlists)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::aim::BundlePlaylist>& BundleFile::playlists() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:aim.BundleFile.playlists)
  return _internal_playlists();
}
inline const ::google::protobuf::RepeatedPtrField<::aim::BundlePlaylist>&
BundleFile::_internal_playlists() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.playlists_;
}
inline ::google::protobuf::RepeatedPtrField<::aim::BundlePlaylist>* PROTOBUF_NONNULL
BundleFile::_internal_mutable_playlists() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.playlists_;
}

// repeated .aim.BundleGuide guides = 3;
inline int BundleFile::_internal_guides_size() const {
  return _internal_guides().size();
}
inline int BundleFile::guides_size() const {
  return _internal_guides_size();
}
inline void BundleFile::clear_guides() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.guides_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::aim::BundleGuide* PROTOBUF_NONNULL BundleFile::mutable_guides(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:aim.BundleFile.guides)
  return _internal_mutable_guides()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::aim::BundleGuide>* PROTOBUF_NONNULL BundleFile::mutable_guides()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_mutable_list:aim.BundleFile.guides)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_guides();
}
inline const ::aim::BundleGuide& BundleFile::guides(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:aim.BundleFile.guides)
  return _internal_guides().Get(index);
}
inline ::aim::BundleGuide* PROTOBUF_NONNULL BundleFile::add_guides()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::aim::BundleGuide* _add =
      _internal_mutable_guides()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_add:aim.BundleFile.guides)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::aim::BundleGuide>& BundleFile::guides() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:aim.BundleFile.guides)
  return _internal_guides();
}
inline const ::google::protobuf::RepeatedPtrField<::aim::BundleGuide>&
BundleFile::_internal_guides() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.guides_;
}
inline ::google::protobuf::RepeatedPtrField<::aim::BundleGuide>* PROTOBUF_NONNULL
BundleFile::_internal_mutable_guides() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.guides_;
}

// -------------------------------------------------------------------

// BundleInfo

// string bundle_name = 1;
inline bool BundleInfo::has_bundle_name() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  return value;
}
inline void BundleInfo::clear_bundle_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.bundle_name_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& BundleInfo::bundle_name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:aim.BundleInfo.bundle_name)
  return _internal_bundle_name();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void BundleInfo::set_bundle_name(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.bundle_name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:aim.BundleInfo.bundle_name)
}
inline ::std::string* PROTOBUF_NONNULL BundleInfo::mutable_bundle_name()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_bundle_name();
  // @@protoc_insertion_point(field_mutable:aim.BundleInfo.bundle_name)
  return _s;
}
inline const ::std::string& BundleInfo::_internal_bundle_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.bundle_name_.Get();
}
inline void BundleInfo::_internal_set_bundle_name(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.bundle_name_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL BundleInfo::_internal_mutable_bundle_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.bundle_name_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE BundleInfo::release_bundle_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:aim.BundleInfo.bundle_name)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.bundle_name_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.bundle_name_.Set("", GetArena());
  }
  return released;
}
inline void BundleInfo::set_allocated_bundle_name(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.bundle_name_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.bundle_name_.IsDefault()) {
    _impl_.bundle_name_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:aim.BundleInfo.bundle_name)
}

// bool readonly = 2;
inline bool BundleInfo::has_readonly() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  return value;
}
inline void BundleInfo::clear_readonly() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.readonly_ = false;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline bool BundleInfo::readonly() const {
  // @@protoc_insertion_point(field_get:aim.BundleInfo.readonly)
  return _internal_readonly();
}
inline void BundleInfo::set_readonly(bool value) {
  _internal_set_readonly(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:aim.BundleInfo.readonly)
}
inline bool BundleInfo::_internal_readonly() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.readonly_;
}
inline void BundleInfo::_internal_set_readonly(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.readonly_ = value;
}

// bool archived = 3;
inline bool BundleInfo::has_archived() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000004U);
  return value;
}
inline void BundleInfo::clear_archived() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.archived_ = false;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline bool BundleInfo::archived() const {
  // @@protoc_insertion_point(field_get:aim.BundleInfo.archived)
  return _internal_archived();
}
inline void BundleInfo::set_archived(bool value) {
  _internal_set_archived(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:aim.BundleInfo.archived)
}
inline bool BundleInfo::_internal_archived() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.archived_;
}
inline void BundleInfo::_internal_set_archived(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.archived_ = value;
}

// -------------------------------------------------------------------

// BundleInfoFile

// repeated .aim.BundleInfo bundles = 1;
inline int BundleInfoFile::_internal_bundles_size() const {
  return _internal_bundles().size();
}
inline int BundleInfoFile::bundles_size() const {
  return _internal_bundles_size();
}
inline void BundleInfoFile::clear_bundles() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.bundles_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::aim::BundleInfo* PROTOBUF_NONNULL BundleInfoFile::mutable_bundles(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:aim.BundleInfoFile.bundles)
  return _internal_mutable_bundles()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::aim::BundleInfo>* PROTOBUF_NONNULL BundleInfoFile::mutable_bundles()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:aim.BundleInfoFile.bundles)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_bundles();
}
inline const ::aim::BundleInfo& BundleInfoFile::bundles(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:aim.BundleInfoFile.bundles)
  return _internal_bundles().Get(index);
}
inline ::aim::BundleInfo* PROTOBUF_NONNULL BundleInfoFile::add_bundles()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::aim::BundleInfo* _add =
      _internal_mutable_bundles()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:aim.BundleInfoFile.bundles)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::aim::BundleInfo>& BundleInfoFile::bundles() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:aim.BundleInfoFile.bundles)
  return _internal_bundles();
}
inline const ::google::protobuf::RepeatedPtrField<::aim::BundleInfo>&
BundleInfoFile::_internal_bundles() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.bundles_;
}
inline ::google::protobuf::RepeatedPtrField<::aim::BundleInfo>* PROTOBUF_NONNULL
BundleInfoFile::_internal_mutable_bundles() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.bundles_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace aim


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // bundle_2eproto_2epb_2eh
